language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "violet_vines-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: violet-vines
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: QSLsib3KduSDNMxTpzwTtYxd/1a0H1Wn5+gaELry16yVLjhI4Tmzick81yrvEwE4utiIw/6rHJAYryo11XYsIocFTH9vt9hK8vw0/KQYibkDiY4BifD4cMH/fOGgNuzDJ2Jv1G/tzim0qY1kigHR27vDctG/uUD5HYp7fXmy8+K82zPGOlL6AH4+g/aICtj6h/e/wwZoyBtxqPbvbn3OWsrsUmTWZppM9d/tw0RJeYWA7T4hXkEVgteBk2DDNHd63s/5/lufk8M6DoFAaBOMUlhLB4RDgW8ChM8AIUSP6wi0AKZ+BgzFAfEcpYFZlJdAWGmPAaVEFgXe2hhD3Orp1dWXrXrBU7FE931t0ObU+KrKCDd6xoFYYvUboObfKSmEmaczxXDbZ8Kbb8U2GHIPlMROJ6jbTI4YY61Hxb7BpmncRq36Rput/oWP4WBG7Umu79kumQ/oYK/MnGKs477mlrRTTc+zUyM2pvVdwsllGfwdkRfj6Uk1nxRSpUIv0vDg4eEaHe8lPYinY22GskbHnp4k/RhYlAI3dlM9lvc5tR7Io8jJfjMaCwZepkUHsPPwCgS8FKQH7Ymi8l4zrgCHom5gt9UN2QeFP4DbIp2CeoA0O+7JKDqkRaIoJRhtS4ps87XqcPPno0qUAdtyDNnPLz7++8FADKPedx4htjAkTP8=
