language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: violet-vines
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: jPF4pzBkFSuovCxMfHbYt7rmKBv0x+5ZNT0MYa56A5zlABgtjXHH2R3yk9nMAC8JERuHu1SEkR/9F2TIXxeH049Z/0280+D7wquNlazj643o8Q8/ODfAN6nlQMhgJ97r9vINLhHPQb9JSs9bEzhJ0UR5qvTn1x+GCYFcAnnm9cv/cohU6Qjt9r2MZT44gty3/Fzl+nYUAU2iGK13yEDaQq5JKDelNHVmQTYMOumBr9d6+wHrRF/RQ0+5GylWO8zdHttAIeBAbMiyBWmu1w3xSVeC7m8PJYX5vonm+iDFOfunh8SGopGJtMtcO4UOxHBZu3zSQRgdZSmqJwtDzeWBnbAxXzXdyqiTVbio8138v7uhvYzA4RMe7CJaMNfuvn/NTJkkJI3z6o6Jzy065tdA3sQFrnXG9k363k71/UoA5McaQMr4R7oJhztwPPN+p3GKshe+pn6dEd3Tn0hqbrwnZH8ENrnT6C/XAVqxzMk1jmblR8AIPt1HqSD8Uc3Ln4q9bFvnSG4XxQAhePSmHYpNegALTQvpDmh67BBbNofMw1Y+EMxEg2OadClE3/+zW88guKwOgJ1KyPUyB/yP9+JzNh/q7hwsbISAHtV4QvCdrY8+9hVZMJDNAVL+IBDp7Ep1eUwIR2qdNi20bPnt+URITHNPtN+X/t/VjVbmPPdG/co=
