language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "violet_vines-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: violet-vines
  # the secure key indicates an encrypted value; see README
  api_key:
<<<<<<< HEAD
    secure: UgbNSdeGM99nZ6Ag3MuAeb/Af0kxZZz9Ugtaa/0m2wETo24RnjQsCBplBXIg61O2i2WlQOlf8+2jb2TCZg981KzPFOfZ6+WATGG3HO5cuziIif4LfVgRPIfVcRu5FDdJ6VO+olPigzrG7rE0GSwSJ0b9PtF3c4hev4xR9WM6XYZhS+768OqB/1QlEZrjJ3g0DmHsktReCj+GGFHsMPL6lOI/Jz5HXoa2pF3GVnicD2TE0Crbks3EzaT2JBTgYBTgaUjd2QUyVgPPBXET9K31B9y0U+17xJiGwr0RsTLql0gRvlfVtmqCdF09FHmD9amGtOZLpbbsS6SHu05gdRundhl8W7afA9V9538NER3xBNhaCxXrcKzEHezBwGJVZi//BG7pQGwSaoiReIUocc48xzx33QMU/ZEBmfeeH1FE6+xTgJq2yDkeF1HEGhj+HJh1pOJ0pl2++WT4FJzKDj+nupBrLtpcW7gGj20rcAqMw4PmfpRGmKFh7Tmp+2zanC1zKrV2SICADgP4T1nL3i6gNMrIwmqGZVJAxgVj3dE80rrQdSu6TQCuuuX3zWLKnGGn0amPL0svr6KbIrDHa22UTyP/iZtoFNQO7VJIVBvfrtDxVob5GQvQ+jMt7Jl1Kv8qsEQQToEfWsLCqQeKuQTEgx5Lif5RzLxgbGqrTdTbB40=
=======
    secure: jPF4pzBkFSuovCxMfHbYt7rmKBv0x+5ZNT0MYa56A5zlABgtjXHH2R3yk9nMAC8JERuHu1SEkR/9F2TIXxeH049Z/0280+D7wquNlazj643o8Q8/ODfAN6nlQMhgJ97r9vINLhHPQb9JSs9bEzhJ0UR5qvTn1x+GCYFcAnnm9cv/cohU6Qjt9r2MZT44gty3/Fzl+nYUAU2iGK13yEDaQq5JKDelNHVmQTYMOumBr9d6+wHrRF/RQ0+5GylWO8zdHttAIeBAbMiyBWmu1w3xSVeC7m8PJYX5vonm+iDFOfunh8SGopGJtMtcO4UOxHBZu3zSQRgdZSmqJwtDzeWBnbAxXzXdyqiTVbio8138v7uhvYzA4RMe7CJaMNfuvn/NTJkkJI3z6o6Jzy065tdA3sQFrnXG9k363k71/UoA5McaQMr4R7oJhztwPPN+p3GKshe+pn6dEd3Tn0hqbrwnZH8ENrnT6C/XAVqxzMk1jmblR8AIPt1HqSD8Uc3Ln4q9bFvnSG4XxQAhePSmHYpNegALTQvpDmh67BBbNofMw1Y+EMxEg2OadClE3/+zW88guKwOgJ1KyPUyB/yP9+JzNh/q7hwsbISAHtV4QvCdrY8+9hVZMJDNAVL+IBDp7Ep1eUwIR2qdNi20bPnt+URITHNPtN+X/t/VjVbmPPdG/co=
>>>>>>> bfbbf566a776b05f2733ec020e5293483238add4
